### ISSUE TITLE
Masternode Keeps Stopping

### ISSUE THREAD

**Issue by supercryptogeek** [SocialSend/SocialSend#13]
Not sure if this is an issue on the wallet side or configuration side. Looking for more resources on how to fix.

**Comment by WaterTrooper** [comment]
Its more than likely a config issue. If you join our Discord: https://discord.gg/xJthHER 
you can PM me there or get help in on of our channels.

**Comment by smyers119** [comment]
Closed due to lack of information.  Will re-open if more information is added.
