### ISSUE TITLE
does not sync with latest daemon

### ISSUE THREAD

**Issue by buildsr** [SocialSend/SocialSend#28]
using sendd daemon v 1020105
sync up to 31 block than says "error proof of work DWG prefork"
with using bootstrap file  sync normal

**Comment by 2a5A1Ghu1** [comment]
This is a known issue and should be fixed in our next release. Using our snapshot/boostrap or using an older version of the social send wallet to sync past block 31 is the only current work around.

We should have a new release hopefully very soon.
